# Database Configuration
db.url=jdbc:mysql://YOUR_HOST:YOUR_PORT/YOUR_DATABASE?sslMode=REQUIRED
db.username=YOUR_USERNAME
db.password=YOUR_DATABASE_PASSWORD

# API Keys
gemini.api.key=YOUR_GEMINI_API_KEY
sendgrid.api.key=YOUR_SENDGRID_API_KEY
sendgrid.from.email=YOUR_EMAIL
